### ISSUE TITLE
Workable for other systems than dnd

### ISSUE THREAD

**Issue by knightje** [jackkerouac/animated-spell-effects-cartoon#1]
Is there any way to make a user interface like FXMaster to use ur Spell Effects with a simple mouseclick?
So that there is a button on the left screen with a preview of the spell, selecting it and displaying it by clicking on ur screen?

**Comment by krysztalzg** [comment]
We can create FXMaster effects manually, but it would be great if this module could import itself into FX Master by default 🚀
