### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by Armandeus66** [jackkerouac/animated-spell-effects-cartoon#4]
When trying to install this, Foundry v10 gives these errors:

foundry.js:58526 Errors were encountered while installing the package. Consult your console log (F12) for details.
fetch @ foundry.js:58526
setup.js:141 [animated-spell-effects-cartoon] Metadata validation failed for module "animated-spell-effects-cartoon": The file "scripts/settings.js" included by module animated-spell-effects-cartoon does not exist
#logPackageWarnings @ setup.js:141
setup.js:145 [animated-spell-effects-cartoon] The module "animated-spell-effects-cartoon" contains "dependencies" which is deprecated in favor of "relationships.requires"
#logPackageWarnings @ setup.js:145
setup.js:145 [animated-spell-effects-cartoon] The module "animated-spell-effects-cartoon" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by ThingsCouldGetDicey** [comment]
i was about to report a similar thing. it just wont install.
